# Generated by Django 3.2.10 on 2021-12-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_back', '0003_auto_20211208_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stuff_back.group'),
            preserve_default=False,
        ),
    ]
